### ISSUE TITLE
TRNLHostEvent - trashing variables

### ISSUE THREAD

**Issue by JernejL** [BeRo1985/rnl#5]
If -gt compiler option is used in freepascal, which i use frequent to identify uninitialized variables, RNL fails to function correctly: 
 
Without -gt EnetHost.Service has correct data: 
https://i.imgur.com/Y3BYB8H.png
 
With -gt, you can see that not all data is properly initialized to event parameter: 
https://i.imgur.com/tbs3Gf4.png
 
This happens on call to fEventQueue.Dequeue within TRNLHost.DispatchIteration. 
 
There is a call to: TRNLQueue<T>.Dequeue - when fCount>0 fails, OUT parameter result becomes undefined.
 
In your example, you use (Server.Service(Event,1000)<>RNL_HOST_SERVICE_STATUS_ERROR) to check if event is to be processed, but not if it's RNL_HOST_SERVICE_STATUS_TIMEOUT - which is the case where event's message will be invalid data, your example would also crash if compiled with -gt switch, i'd recommend just leaving the event as-is if there's nothing to deque - maybe by changing parameter from out to var parameter, leaving the original, blank initialized struct in return.

**Comment by JernejL** [comment]
(Tenethostevent.free will also fail in this case)

**Comment by BeRo1985** [comment]
Please test it again

**Comment by BeRo1985** [comment]
Closed due to no answer so far
